### ISSUE TITLE
Feature Idea: chess

### ISSUE THREAD

**Issue by DrumsnChocolate** [csvalpha/amber-ui#464]
chess, like this: 
![image](https://user-images.githubusercontent.com/32799956/153266740-5b208b62-6e92-418a-adf6-636e0e381e27.png)

**Comment by HeinHuijskes** [comment]
:eyes:

**Comment by HeinHuijskes** [comment]
As mentioned it would be very nice to use JavaScript packages for game logic, it saves a lot of hassle. 
Currently testing: [chess.js](https://github.com/jhlywa/chess.js)  
Also promising: [Multiplayer chess.js](https://yarnpkg.com/package/chess.js-multiplayer-client)

It does seem epic to me to build an ELO system and accompanying rank display page somewhat from the ground up ourselves, since this could incorporate much more of our own ideas and logic. 

Also it might finally start teaching me how amber-ui actually works after many years :).

**Comment by HeinHuijskes** [comment]
Small list of _(possible eventual)_ features since I am way too hyped for this
Must have:
- [x] Functioning board
- [ ] Package for logic and validation
- [ ] Game state saving on page reload (backend)

Want to have:
- [ ] Prettier movement (e.g. dragging and dropping)
- [ ] Multiplayer
- [ ] ELO system (backend)

Wish to have:
- [ ] Move option indicators
- [ ] Multiple styling choices/preferences
- [ ] AI to play against
- [ ] Multiple AI levels to play against
